---
- hosts: devops
  user: ubuntu
  sudo: yes
  tasks:
     - name: installing git
       apt: name=git state=present
     - name: cloning hit repository
       git: repo=https://github.com/kktelaprolu/java.git dest=/home/ubuntu/kk
