---
- hosts: devops
  user: ubuntu
  sudo: yes
  tasks:
      - name: installing packages
        apt: name={{ item }} state=present
        with_items:
              - vim
              - ufw
              - tree
              - telnet
